export type Tier={name:string;price:string;features:string[]}
export type Service={slug:string;name:string;icon:string;tagline:string;desc:string;points:string[];tiers:Tier[]}
const T=(a:string,b:string,c:string,fa:string[],fb:string[],fc:string[]):Tier[]=>[{name:a,price:'Custom',features:fa},{name:b,price:'Custom',features:fb},{name:c,price:'Custom',features:fc}]
export const services:Service[]=[
 {slug:'diesel-supply',name:'Diesel Supply',icon:'⛽',tagline:'High quality diesel with the best price',desc:'We supply tested and trusted diesel to hotels, restaurants, companies, estates, residents and more, with a personalized approach and the best price.',points:['Diesel supply to hotels, restaurants, companies, estates & residents','High quality, tested & trusted diesel','Competitive, honest pricing','Reliable scheduled deliveries','A personalized approach for every customer'],tiers:T('Retail','Bulk Supply','Contract Supply',['Small to medium volumes','Quick delivery','Phone & WhatsApp ordering'],['Large volume orders','Best bulk pricing','Priority scheduling','Delivery confirmation'],['Long-term supply agreement','Dedicated account contact','Flexible payment terms','Consistent quality assurance'])},
 {slug:'petroleum-products',name:'Petroleum Products',icon:'🛢️',tagline:'Supplier of petroleum products you can depend on',desc:'Sourcing and supply of petroleum products for industrial, commercial and retail customers across Lagos and beyond.',points:['Petroleum products supply','Drum & bulk quantities','Quality-assured sourcing','Responsive customer support'],tiers:T('Standard Order','Bulk Order','Corporate',['Drum quantities','Fast quotation','Pickup or delivery'],['Bulk quantities','Preferred pricing','Scheduled delivery','Quality documentation'],['Recurring supply contract','Account manager','Priority fulfilment','Tailored terms'])},
 {slug:'lubricants',name:'Lubricants & Engine Oils',icon:'🧴',tagline:'Protect every engine, every journey',desc:'Genuine lubricants and engine oils in drums and containers for vehicles, generators and heavy machinery.',points:['Engine oils & lubricants','Drums, jerrycans & containers','Fleet & generator lubrication supply','Genuine, quality products'],tiers:T('Starter Pack','Workshop Pack','Distributor',['Retail containers','Product guidance','Quick pickup'],['Drum quantities','Better unit pricing','Regular restocking','Delivery included'],['Wholesale volumes','Distributor pricing','Priority restocking','Dedicated contact'])},
 {slug:'tanker-haulage',name:'Tanker Haulage & Delivery',icon:'🚚',tagline:'Delivered safely, on time',desc:'Our branded tanker trucks deliver diesel and petroleum products straight to your site with care and accountability.',points:['Tanker truck delivery','Direct-to-site supply','Scheduled & emergency runs','Safe, accountable handling'],tiers:T('Single Delivery','Weekly Runs','Dedicated Fleet',['One-off delivery','Lagos coverage','Delivery confirmation'],['Recurring deliveries','Fixed scheduling','Priority dispatch','Status updates'],['Dedicated tanker allocation','Contract rates','Account manager','Custom logistics plan'])},
 {slug:'sales-marketing',name:'Sales & Marketing',icon:'📈',tagline:'Connecting quality products to the market',desc:'Professional sales and marketing of petroleum products, helping suppliers and buyers connect with confidence.',points:['Petroleum products sales','Market linkage for suppliers & buyers','Bulk trade support','Honest, transparent dealings'],tiers:T('Buyer Support','Trade Partner','Strategic Partner',['Product sourcing','Price quotations','Order guidance'],['Regular trade supply','Preferred rates','Market updates','Dedicated contact'],['Long-term partnership','Custom trade terms','Joint planning','Account manager'])},
 {slug:'general-contracting',name:'General Contracting',icon:'🏗️',tagline:'Dependable contracting, delivered with integrity',desc:'General contractor services for projects, supply and procurement for corporate, industrial and private clients.',points:['General contract works','Procurement & supply','Project coordination','Integrity-led execution'],tiers:T('Small Project','Standard Project','Major Contract',['Site assessment','Clear scope & quote','Quick mobilization'],['Full project planning','Procurement & supply','Progress reporting','Quality supervision'],['Large-scale contracts','Dedicated project lead','Compliance support','Handover & aftercare'])}
]
export const site={name:'IGOCHE OIL & GAS NIG. LTD.',rc:'1761904',phones:['08037549736','08022925330','08094783639','08058090569'],phone:'08037549736',wa:'2348037549736',waDisplay:'08037549736',email:'igocheoilandgasnigerialtd2202@gmail.com',address:'16, Water Co-operation Drive, Opposite Landmark, Victoria Island, Lagos State',md:'Igoche Sunday',role:'Managing Director',tagline:'Supplier of Petroleum Products, Sales, Marketing & General Contractor'}
export const handle='igocheoilandgasnigltd'
export const socials:[string,string,string][]=[['instagram','Instagram',`https://instagram.com/${handle}`],['facebook','Facebook',`https://facebook.com/${handle}`],['whatsapp','WhatsApp',`https://wa.me/${site.wa}`]]
export const clients:[string,string][]=[['🏨','Hotels'],['🍽️','Restaurants'],['🏢','Companies'],['🏘️','Estates'],['🏠','Residents'],['🏭','Industries & more']]
// Free-licence Unsplash photos (photo page IDs). Each falls back to the local /public/img/<slug>.jpg if offline/blocked.
export const unsplash:Record<string,string>={'tanker-haulage':'CY4ce8XOLHo','petroleum-products':'O2XbR4lXhDM','diesel-supply':'kInJXRQVOss'}
export const bySlug=(s:string)=>services.find(x=>x.slug===s)!
export const NAV:[string,string][]=[['/','Home'],['/about','About'],['/services','Services'],['/packages','Packages'],['/contact','Contact']]
